#!/bin/bash

echo "Pulling image"

docker pull mewchildy/spring-boot-docker-aws:latest

echo "List running images"

docker ps -a

echo "Run image"

docker run -d --name spring-boot -p 8080:8080 mewchildy/spring-boot-docker-aws 
