format_version: 10
pipelines:
  build-app:
    group: HelloWorld
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c240b63:
        git: https://github.com/mewchildy/HelloWorld.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build-and-Pull:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            resources:
            - dev
            tasks:
            - exec:
                command: echo
                arguments:
                - "build application"
                run_if: passed
          pull:
            timeout: 0
            resources:
            - dev
            tasks:
            - exec:
                command: make
                arguments:
                - pull
                run_if: passed
