#!/bin/bash

echo "Pulling image"

sudo docker pull mewchildy/spring-boot-docker-aws:latest

echo "List running images"

sudo docker ps -a

echo "Run image"

sudo docker run -d --name spring-boot -p 8080:8080 mewchildy/spring-boot-docker-aws 
