format_version: 10
pipelines:
  deploy:
    group: HelloWorld
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      upstream:        
          pipeline: test
          stage: test
          name: upstream_pipeline      
      SourceCodeRepo:
        git: https://github.com/mewchildy/HelloWorld.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            resources:
            - dev
            tasks:
            - exec:
                command: make
                arguments: 
                - deploy           
                run_if: passed
            - fetch:
                pipeline: test
                stage: test
                job: test
                source: index.html
                run_if: passed
