format_version: 10
pipelines:
  deploy:
    group: HelloWorld
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      upstream:        
          pipeline: test
          stage: test
          name: upstream_pipeline      
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run:
            timeout: 0
            resources:
            - dev
            tasks:
            - exec:
                command: echo
                arguments: "Deployed!"                
                run_if: passed
