format_version: 10
pipelines:
  deploy:
    group: HelloWorld
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      MyFirstPipeline:
        ignore_for_scheduling: false
        pipeline: built-app
        stage: Build-and-Test
    stages:
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - deployed!
                command: echo
                run_if: passed
    - production:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy-to-prod:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '"production deployed"'
                command: echo
                run_if: passed
