format_version: 10
pipelines:
  test:
    group: HelloWorld
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      build-app:
        ignore_for_scheduling: false
        pipeline: build-app
        stage: Build-and-Run
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            resources:
            - dev
            tasks:
            - exec:
                command: make
                arguments:
                - test                
                run_if: passed
